# Generated by Django 5.1.2 on 2024-12-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('manufacturer', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('silver', 'Silver'), ('gray', 'Gray'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('brown', 'Brown'), ('orange', 'Orange'), ('purple', 'Purple'), ('metallic_black', 'Metallic Black'), ('metallic_silver', 'Metallic Silver'), ('metallic_gray', 'Metallic Gray'), ('metallic_red', 'Metallic Red'), ('metallic_blue', 'Metallic Blue'), ('metallic_green', 'Metallic Green'), ('metallic_brown', 'Metallic Brown'), ('pearl_white', 'Pearl White'), ('matte_black', 'Matte Black'), ('chrome', 'Chrome'), ('gold', 'Gold'), ('custom', 'Custom Color')], max_length=20)),
                ('body_type', models.CharField(max_length=50)),
                ('engine_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric')], max_length=50)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=50)),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('biodiesel', 'Biodiesel'), ('hydrogen', 'Hydrogen Fuel Cell'), ('ethanol', 'Ethanol (Flex-Fuel)')], max_length=50)),
                ('seating_capacity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('sold', 'Sold')], max_length=20)),
                ('registration_date', models.DateField()),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
    ]
